

const ESTATUAS = {
  tipo: [
    'Estátua',
    'Estátua pequena',
    'Estátua de tamanho real',
    'Estátua',
    'Estátua',
    'Estátua',
    'Busto',
    'Busto',
    'Busto',
    'Taxidermia',
    'Taxidermia',
    'Escultura renascentista',
    'Escultura barroca',
    'Escultura neoclássica',
    'Escultura modernista',
  ],
  arte: [
    'de um homem',
    'de um homem com uma arma de fogo',
    'de um homem acadêmico',
    'de um leão',
    'de um tigre',
    'de um alce',
    'de um urso',
    'de um unicórnio',
    'de uma mulher',
    'de uma mulher com um livro',
    'de uma mulher com uma baçança',
    'de uma mulher acadêmica',
    'de um anjo',
    'de um diabo',
    'de um homem ferido',
    'de uma mulher ferida',
    'de um padre',
    'de uma freira',
    'de um caçador',
    'de um pintor',
    'de um político',
    'de um policial',
    'de um homem de terno',
    'de uma mulher de terno',
    'de um cientista',
    'de uma cientista',
  ],
  taxidermia: [
    'de um leão',
    'de um tigre',
    'de um alce',
    'de um gato-do-mato',
    'de um tucano',
    'de um pinguim',
    'de um pato',
    'de um ornitorrinco',
    'da cabeça de um urso',
    'de um urso',
    'da cabeça de um alce',
    'da cabeça de um leão',
    'de um castor',
  ],
  detalhes: [
    'com marcas de pichação',
    'sem assinatura',
    'com uma palavra rasurada',
    'com números rasurados',
    'manchado de sangue',
    'quebrado',
    'rachado',
    'incompleto',
    'de um artista famoso',
    'de um artista desconhecido',
  ],
};


function rolarEstatua(callback) {
  let index_tipo = Math.floor(Math.random() * ESTATUAS.tipo.length);
  let tipo = ESTATUAS.tipo[index_tipo];

  let arte = '';
  if (tipo == 'Taxidermia') {
    let index_arte = Math.floor(Math.random() * ESTATUAS.taxidermia.length);
    arte = ESTATUAS.taxidermia[index_arte];
  } else {
    let index_arte = Math.floor(Math.random() * ESTATUAS.arte.length);
    arte = ESTATUAS.arte[index_arte];
  }

  let detalhes = '';
  let tem_detalhes = Math.floor(Math.random() * 3) > 1;
  if (tem_detalhes) {
    let index_detalhe = Math.floor(Math.random() * ESTATUAS.detalhes.length);
    let detalhe = ESTATUAS.detalhes[index_detalhe];
    detalhes = `, ${detalhe}`;
  }

  let retorno = `${tipo} ${arte}${detalhes}`;
  callback(retorno);
}

function rolarTaxidermia(callback) {
  let tipo = 'Taxidermia';

  let index_arte = Math.floor(Math.random() * ESTATUAS.taxidermia.length);
  let arte = ESTATUAS.taxidermia[index_arte];

  let detalhes = '';
  let tem_detalhes = Math.floor(Math.random() * 3) > 1;
  if (tem_detalhes) {
    let index_detalhe = Math.floor(Math.random() * ESTATUAS.detalhes.length);
    let detalhe = ESTATUAS.detalhes[index_detalhe];
    detalhes = `, ${detalhe}`;
  }

  let retorno = `${tipo} ${arte}${detalhes}`;
  callback(retorno);
}


const QUADROS = {
  molduras: [
    'moldura de bronse',
    'moldura de madeira',
    'moldura de madeira',
    'moldura de madeira',
    'moldura dourada',
    'moldura prateada',
  ],
  tipos_pintura: [
    'pintura à óleo',
    'pintura aquarela',
    'pintura acrílica',
    'pintura guache',
    'pintura em pastel',
    'afresco',
    'fotografia',
    'fotografia',
    'fotografia',
    'fotografia',
  ],
  desenho: [
    'de casas',
    'de um jardim',
    'de um senhor idoso',
    'de uma senhora idosa',
    'de um casal',
    'de pássaros',
    'de uma árvore',
    'de uma flor',
    'de uma mansão',
    'de um castelo',
    'de um vaso',
    'impressionista',
    'com desenho abstrato',
    'de uma ruela',
    'de um barco',
    'do céu com núvens',
    'de pessoas andando',
    'de um animal',
    'de um homem',
    'de uma mulher',
    'de pessoas rezando',
    'de um animal morto',
    'de um lampião',
    'de uma montanha',
    'de uma mesa com frutas',
    'de um quarto',
    'de uma pessoa enforcada',
    'de uma floresta',
    'de um rio',
    'de uma pradaria',
  ],
  foto: [
    'de casas',
    'de um jardim',
    'de um senhor idoso',
    'de uma senhora idosa',
    'de um casal',
    'de pássaros',
    'de uma árvore',
    'de uma flor',
    'de uma mansão',
    'de um castelo',
    'de um vaso',
    'de uma ruela',
    'de um barco',
    'do céu com núvens',
    'de pessoas andando',
    'de um animal',
    'de um homem',
    'de uma mulher',
    'de pessoas rezando',
    'de um animal morto',
    'de um lampião',
    'de uma montanha',
    'de uma mesa com frutas',
    'de um quarto',
    'de uma floresta',
    'de um rio',
    'de uma pradaria',
    'da cidade',
    'do pôr do sol',
    'de um político',
    'de um carro',
    'de uma atriz',
  ],
  detalhes: [
    'com cores diversas',
    'sem assinatura',
    'com uma palavra rasurada',
    'com números rasurados',
    'manchado de sangue',
    'rasgado',
    'de cores claras',
    'de cores escuras',
    'incompleto',
    'de um pintor famoso',
    'de um pintor desconhecido',
  ],
  detalhes_fotografia: [
    'preto e branco',
    'vintage',
    'com uma palavra rasurada',
    'com números rasurados',
    'manchado de sangue',
    'rasgada',
    'desbotada',
  ],
};

function rolarQuadro(callback) {
  let index_moldura = Math.floor(Math.random() * QUADROS.molduras.length);
  let moldura = QUADROS.molduras[index_moldura];

  let index_tipo_pintura = Math.floor(Math.random() * QUADROS.tipos_pintura.length);
  let tipo_pintura = QUADROS.tipos_pintura[index_tipo_pintura];

  let desenho = '';
  let detalhes = '';
  let tem_detalhes = Math.floor(Math.random() * 3) > 1;

  if (tipo_pintura == 'fotografia') {
    let index_desenho = Math.floor(Math.random() * QUADROS.foto.length);
    desenho = QUADROS.foto[index_desenho];

    if (tem_detalhes) {
      let index_detalhe = Math.floor(Math.random() * QUADROS.detalhes_fotografia.length);
      let detalhe = QUADROS.detalhes_fotografia[index_detalhe];
      detalhes = `, ${detalhe}`;
    }
  } else {
    let index_desenho = Math.floor(Math.random() * QUADROS.desenho.length);
    desenho = QUADROS.desenho[index_desenho];

    if (tem_detalhes) {
      let index_detalhe = Math.floor(Math.random() * QUADROS.detalhes.length);
      let detalhe = QUADROS.detalhes[index_detalhe];
      detalhes = `, ${detalhe}`;
    }
  }

  let quadro = `Quadro com ${moldura}, ${tipo_pintura} ${desenho}${detalhes}`;
  callback(quadro);
}

const LUGARES = {
  'vestibulo': [
    'Espelho',
    'Carpete',
    'Vaso com plantas',
    'Quadro',
    'Lampião',
    'Relógio de pêndulo',
    'Chapeleira',
    'Mesa decorativa',
    'Poltrona de um lugar',
    'Cabideiro',
    'Vaso decorativo',
    'Arca',
    'Banqueta',
    'Sofá de um lugar',
    'Pia',
    'Espelho de maquiagem',
    'Espelho de rosto',
    'Penteadeira',
    'Baú',
    'Cômoda',
    'Guarda-roupa pequeno',
    'Guarda-roupa médio',
    'Guarda-roupa grande',
    'Fraldário',
    'Armário infantil',
    'Guarda-roupa infantil',
    'Entulhos espalhados',
    'Cadeira de madeira',
    'Cadeira de metal',
    'Cadeira de balanço',
    'Arara de camisas',
  ],
  'escritorio': [
    'Carpete',
    'Vaso com plantas',
    'Quadro',
    'Quadro',
    'Quadro',
    'Quadro',
    'Relógio de pêndulo',
    'Computador',
    'Notebook',
    'Escrivaninha',
    'Relógio eletrônico',
    'Telefone',
    'Aparelho de Fax',
    'Impressora',
    'Câmera de Vigilância',
    'Cofre manual',
    'Cofre eletrônico',
    'Ventilador',
    'Arquivo de metal',
    'Vaso decorativo',
    'Arca',
    'Sofá de um lugar',
    'Tripé com Telescópico',
    'Tripé com Filmadora',
    'Tripé com Câmera',
    'Baú',
    'Criado mudo',
    'Cômoda',
    'Estante de livros',
    'Mesa redonda',
    'Mesa quadrada',
    'Mesa pequena',
    'Destroços',
    'Alavanca de pressão',
    'Alavanca mecânica',
    'Alavanca eletrônica',
    'Cofre mecânico',
    'Cofre computadorizado',
    'Molduras sobressalentes',
    'Caixas de metal fechadas',
    'Caixas de plástico fechadas',
    'Caixas de papelão fechadas',
    'Divã',
    'Retroprojetor',
    'Entulhos espalhados',
    'Aparelho de som',
    'Aparelho de CD',
    'Aparelho de DVD',
    'Caixa de som',
  ],
  'quarto': [
    'Cama de solteiro',
    'Cama de casal',
    'Espelho',
    'Carpete',
    'Vaso com plantas',
    'Quadro',
    'Estátua',
    'Taxidermia',
    'Lampião',
    'Relógio de pêndulo',
    'Chapeleira',
    'Mesa decorativa',
    'Poltrona de um lugar',
    'Cabideiro',
    'Computador',
    'Notebook',
    'Escrivaninha',
    'Relógio eletrônico',
    'Telefone',
    'Televisão',
    'Cofre manual',
    'Cofre eletrônico',
    'Ventilador',
    'Vaso decorativo',
    'Arca',
    'Banqueta',
    'Sofá de um lugar',
    'Espelho de maquiagem',
    'Espelho de rosto',
    'Penteadeira',
    'Baú',
    'Aparador',
    'Lareira',
    'Criado mudo',
    'Cômoda',
    'Brinquedos de criança',
    'Guarda-roupa pequeno',
    'Guarda-roupa médio',
    'Guarda-roupa grande',
    'Violão',
    'Berço',
    'Cama de criança',
    'Armário infantil',
    'Guarda-roupa infantil',
    'Alavanca mecânica',
    'Arara de camisas',
    'Aparelho de som',
    'Tapete infantil',
  ],
  'quarto_de_crianca': [
    'Carpete',
    'Vaso com plantas',
    'Quadro',
    'Televisão',
    'Espelho de rosto',
    'Penteadeira',
    'Baú',
    'Cômoda',
    'Estante de livros',
    'Estante de medicamentos',
    'Berço',
    'Brinquedos de criança',
    'Brinquedos de criança',
    'Brinquedos de criança',
    'Brinquedos de criança',
    'Guarda-roupa pequeno',
    'Guarda-roupa médio',
    'Berço',
    'Berço',
    'Berço',
    'Balança de bebe',
    'Cama de criança',
    'Fraldário',
    'Armário infantil',
    'Guarda-roupa infantil',
    'Aparelho de som',
  ],
  'sala': [
    'Espelho',
    'Carpete',
    'Vaso com plantas',
    'Quadro',
    'Quadro',
    'Quadro',
    'Quadro',
    'Quadro',
    'Quadro',
    'Quadro',
    'Estátua',
    'Taxidermia',
    'Lampião',
    'Relógio de pêndulo',
    'Chapeleira',
    'Mesa decorativa',
    'Mesa decorativa',
    'Poltrona de um lugar',
    'Poltrona de dois lugares',
    'Poltrona de um lugar',
    'Poltrona de dois lugares',
    'Poltrona de um lugar',
    'Poltrona de dois lugares',
    'Relógio eletrônico',
    'Telefone',
    'Câmera de Vigilância',
    'Televisão',
    'Cofre manual',
    'Cofre eletrônico',
    'Ventilador',
    'Vaso decorativo',
    'Vaso decorativo',
    'Vaso decorativo',
    'Arca',
    'Banqueta',
    'Sofá de um lugar',
    'Sofá de dois lugares',
    'Sofá de três lugares',
    'Sofá de um lugar',
    'Sofá de dois lugares',
    'Sofá de três lugares',
    'Sofá de um lugar',
    'Sofá de dois lugares',
    'Sofá de três lugares',
    'Castiçal de velas',
    'Mesa com cadeiras',
    'Cristaleira',
    'Baú',
    'Adega',
    'Carrinho de chá',
    'Aparador',
    'Lareira',
    'Criado mudo',
    'Cômoda',
    'Brinquedos de criança',
    'Mesa redonda',
    'Mesa quadrada',
    'Mesa pequena',
    'Divã',
    'Altar',
    'Púlpito',
    'Entulhos espalhados',
    'Cadeira de madeira',
    'Cadeira de balanço',
    'Aparelho de som',
    'Aparelho de CD',
    'Aparelho de DVD',
    'Caixa de som',
    'Piano de cauda',
    'Piano vertical',
  ],
  'cozinha': [
    'Quadro',
    'Lampião',
    'Relógio de pêndulo',
    'Vaso decorativo',
    'Banqueta',
    'Castiçal de velas',
    'Mesa com cadeiras',
    'Baú',
    'Barril',
    'Adega',
    'Carrinho de chá',
    'Estante de talheres',
    'Aparador',
    'Cômoda',
    'Bancada com pia',
    'Mesa redonda',
    'Mesa quadrada',
    'Mesa pequena',
    'Exaustor industrial de calor',
    'Latão de lixo',
    'Destroços',
    'Alavanca de pressão',
    'Alavanca mecânica',
    'Alavanca eletrônica',
    'Painel elétrico',
    'Pacotes de saco plástico',
    'Cofre mecânico',
    'Caixas de metal fechadas',
    'Caixas de plástico fechadas',
    'Caixas de papelão fechadas',
    'Balança industrial',
    'Estante de talheres',
    'Tanque',
    'Entulhos espalhados',
    'Cadeira de madeira',
    'Cadeira de metal',
    'Freezer',
    'Geladeira',
    'Fogão',
    'Fogão industrial',
    'Forno analógico',
    'Forno de micro-ondas',
    'Balcão',
    'Prateleira de bebidas',
    'Geladeira de bebidas',
  ],
  'corredor': [
    'Espelho',
    'Carpete',
    'Vaso com plantas',
    'Vaso com plantas',
    'Vaso com plantas',
    'Quadro',
    'Quadro',
    'Quadro',
    'Quadro',
    'Quadro',
    'Relógio de pêndulo',
    'Câmera de Vigilância',
    'Vaso decorativo',
    'Banco de madeira de um lugar',
    'Banco de madeira de dois lugares',
    'Banco de madeira de três lugares',
    'Castiçal de velas',
    'Cristaleira',
    'Carrinho de chá',
    'Aparador',
    'Criado mudo',
    'Cômoda',
    'Estante de livros',
    'Destroços',
  ],
  'sala_de_jantar': [
    'Espelho',
    'Carpete',
    'Vaso com plantas',
    'Quadro',
    'Quadro',
    'Lampião',
    'Relógio de pêndulo',
    'Chapeleira',
    'Mesa decorativa',
    'Vaso decorativo',
    'Banqueta',
    'Castiçal de velas',
    'Mesa com cadeiras',
    'Cristaleira',
    'Baú',
    'Barril',
    'Adega',
    'Távola',
    'Carrinho de chá',
    'Estante de talheres',
    'Aparador',
    'Lareira',
    'Criado mudo',
    'Vitral',
    'Cômoda',
    'Mesa redonda',
    'Mesa quadrada',
    'Mesa pequena',
    'Estante de talheres',
    'Entulhos espalhados',
    'Cadeira de madeira',
    'Caixa de som',
    'Prateleira de bebidas',
    'Geladeira de bebidas',
  ],
  'biblioteca': [
    'Carpete',
    'Vaso com plantas',
    'Quadro',
    'Quadro',
    'Estátua',
    'Taxidermia',
    'Lampião',
    'Relógio de pêndulo',
    'Chapeleira',
    'Mesa decorativa',
    'Poltrona de um lugar',
    'Poltrona de dois lugares',
    'Cabideiro',
    'Computador',
    'Notebook',
    'Escrivaninha',
    'Cofre manual',
    'Vaso decorativo',
    'Arca',
    'Banqueta',
    'Sofá de um lugar',
    'Sofá de dois lugares',
    'Sofá de três lugares',
    'Baú',
    'Carrinho de chá',
    'Aparador',
    'Lareira',
    'Criado mudo',
    'Vitral',
    'Cômoda',
    'Estante de livros',
    'Estante de livros',
    'Estante de livros',
    'Mesa redonda',
    'Mesa quadrada',
    'Mesa pequena',
    'Destroços',
    'Alavanca de pressão',
    'Alavanca mecânica',
    'Alavanca eletrônica',
    'Cofre mecânico',
    'Entulhos espalhados',
    'Piano de cauda',
    'Piano vertical',
  ],
  'jardim': [
    'Estufa de vidro para plantas',
    'Vaso com plantas',
    'Quadro',
    'Estátua',
    'Lampião',
    'Vaso decorativo',
    'Banco de madeira de um lugar',
    'Banco de madeira de dois lugares',
    'Banco de madeira de três lugares',
    'Mesa com cadeiras',
    'Baú',
    'Barril',
    'Aparador',
    'Mesa redonda',
    'Mesa quadrada',
    'Mesa pequena',
    'Latão de lixo',
    'Mangueira sobressalente',
    'Destroços',
    'Carrinho de mão',
    'Sacas de adubo',
    'Sacas de areia',
    'Tanque',
    'Alçapão',
  ],
  'area_externa': [
    'Vaso com plantas',
    'Vaso com plantas',
    'Vaso com plantas',
    'Quadro',
    'Estátua',
    'Estátua',
    'Estátua',
    'Lampião',
    'Vaso decorativo',
    'Vaso decorativo',
    'Vaso decorativo',
    'Arca',
    'Banqueta',
    'Banco de madeira de um lugar',
    'Banco de madeira de dois lugares',
    'Banco de madeira de três lugares',
    'Barril',
    'Távola',
    'Vitral',
    'Mesa redonda',
    'Mesa quadrada',
    'Mesa pequena',
    'Hidrante',
    'Latão de lixo',
    'Tubulação de água',
    'Tubulação de esgoto',
    'Tubulação de gás',
    'Canaleta de cabos',
    'Válvulas de pressão',
    'Válvulas eletrônica',
    'Válvulas mecânica',
    'Latão de lixo',
    'Armário de ferramentas',
    'Mangueira sobressalente',
    'Destroços',
    'Alavanca de pressão',
    'Alavanca mecânica',
    'Alavanca eletrônica',
    'Caixa de transporte',
    'Caixa metálica',
    'Carrinho de transporte de carga',
    'Carrinho de mão',
    'Sacas de cimento',
    'Sacas de areia',
    'Tijolos',
    'Mangueira sobressalente',
    'Hastes de ferro',
    'Tanque',
    'Alçapão',
    'Estufa de vidro para plantas',
    'Altar',
    'Entulhos espalhados',
    'Fonte de água',
    'Fumódromo',
  ],
  'banheiro': [
    'Espelho',
    'Vaso com plantas',
    'Quadro',
    'Vaso decorativo',
    'Arca',
    'Pia',
    'Banheira',
    'Chuveiro',
    'Vaso sanitário',
    'Espelho de maquiagem',
    'Espelho de rosto',
    'Penteadeira',,
    'Criado mudo',
    'Vitral',
    'Cômoda',
    'Fraldário',
    'Lixo',
    'Destroços',
    'Alçapão',
  ],
  'laboratorio': [
    'Vaso com plantas',
    'Quadro',
    'Quadro',
    'Quadro',
    'Quadro',
    'Quadro',
    'Estátua',
    'Taxidermia',
    'Computador',
    'Notebook',
    'Escrivaninha',
    'Relógio eletrônico',
    'Telefone',
    'Aparelho de Fax',
    'Impressora',
    'Câmera de Vigilância',
    'Televisão',
    'Cofre manual',
    'Cofre eletrônico',
    'Ventilador',
    'Sofá de um lugar',
    'Sofá de dois lugares',
    'Tripé com Telescópico',
    'Tripé com Filmadora',
    'Tripé com Câmera',
    'Detector de metais',
    'Microscópio',
    'Colorímetro (equipamento laboratório)',
    'Analisador de bioquímica',
    'Agitador de tubos (vortex)',
    'Agitadores magnéticos',
    'Estufa (equipamento laboratório)',
    'Autoclave (equipamento laboratório)',
    'Balança analítica',
    'Balança semi-analítica',
    'Centrífuga de bancada',
    'Banho-maria (equipamento laboratório)',
    'Dessecador (equipamento laboratório)',
    'Suporte e Pipetas (equipamento laboratório)',
    'Computador Científico',
    'Escrivaninha metálica',
    'Balcão de trabalho',
    'Mesa anti-estática',
    'Sistema de combate a incêndio',
    'Exaustor de segurança',
    'Válvulas de pressão',
    'Monitor computadorizado',
    'Alavanca de pressão',
    'Alavanca mecânica',
    'Alavanca eletrônica',
    'Nobreak industrial',
    'Exaustor industrial de calor',
    'Armário de sobressalentes',
    'Monitor computadorizado',
    'Alavanca de pressão',
    'Alavanca mecânica',
    'Alavanca eletrônica',
    'Latão de lixo',
    'Destroços',
    'Alavanca de pressão',
    'Alavanca mecânica',
    'Alavanca eletrônica',
    'Caixa de transporte',
    'Painel elétrico',
    'Gabinetes de computador',
    'Roupas sobressalentes',
    'Pacotes de saco plástico',
    'Cofre mecânico',
    'Cofre computadorizado',
    'Caixas de metal fechadas',
    'Caixas de plástico fechadas',
    'Caixas de papelão fechadas',
    'Balança industrial',
    'Fogão industrial',
    'Forno analógico',
    'Caixa de som',
  ],
  'sala_tecnologica': [
    'Caixa Registradora',
    'Vaso com plantas',
    'Quadro',
    'Quadro',
    'Quadro',
    'Quadro',
    'Computador',
    'Notebook',
    'Escrivaninha',
    'Relógio eletrônico',
    'Telefone',
    'Aparelho de Fax',
    'Impressora',
    'Câmera de Vigilância',
    'Televisão',
    'Cofre manual',
    'Cofre eletrônico',
    'Ventilador',
    'Sofá de um lugar',
    'Tripé com Telescópico',
    'Tripé com Filmadora',
    'Tripé com Câmera',
    'Microscópio',
    'Computador Científico',    
    'Escrivaninha metálica',
    'Balcão de trabalho',
    'Mesa anti-estática',
    'Monitor computadorizado',
    'Mesa redonda',
    'Mesa quadrada',
    'Mesa pequena',
    'Nobreak industrial',
    'Monitor computadorizado',
    'Canaleta de cabos',
    'Válvulas de pressão',
    'Válvulas eletrônica',
    'Válvulas mecânica',
    'Monitor computadorizado',
    'Destroços',
    'Alavanca de pressão',
    'Alavanca mecânica',
    'Alavanca eletrônica',
    'Resma de folhas',
    'Painel elétrico',
    'Gabinetes de computador',
    'Cofre mecânico',
    'Cofre computadorizado',
    'Divã',
    'Projetor de cinema',
    'Retroprojetor',
    'Entulhos espalhados',
    'Cadeira de madeira',
    'Cadeira de metal',,
    'Aparelho de som',
    'Aparelho de CD',
    'Caixa de som',
    'Geladeira de bebidas',
  ],
  'estoque': [
    'Quadro',
    'Quadro',
    'Computador',
    'Notebook',
    'Câmera de Vigilância',
    'Cofre manual',
    'Cofre eletrônico',
    'Arquivo de metal',
    'Vaso decorativo',
    'Arca',
    'Adega',
    'Estante de livros',
    'Estante de livros',
    'Guarda-roupa médio',
    'Guitarra',
    'Violão',
    'Microscópio',
    'Destroços',
    'Alavanca de pressão',
    'Alavanca mecânica',
    'Alavanca eletrônica',
    'Caixa de transporte',
    'Caixa metálica',
    'Carrinho de transporte de carga',
    'Carrinho de mão',
    'Sacas de cimento',
    'Sacas de areia',
    'Tijolos',
    'Hastes de metal',
    'Bobina de cabos elétricos',
    'Bobina de cabos lógicos',
    'Mangueira sobressalente',
    'Resma de folhas',
    'Hastes de ferro',
    'Molduras de quadro',
    'Sacos com lençóis',
    'Painel elétrico',
    'Gabinetes de computador',
    'Roupas sobressalentes',
    'Pacotes de saco plástico',
    'Cofre mecânico',
    'Cofre computadorizado',
    'Molduras sobressalentes',
    'Caixas de metal fechadas',
    'Caixas de plástico fechadas',
    'Caixas de papelão fechadas',
    'Balança industrial',
    'Retroprojetor',
    'Prateleira de bebidas',
  ],
  'entrada': [
    'Detector de metais',
    'Espelho',
    'Vaso com plantas',
    'Vaso com plantas',
    'Vaso com plantas',
    'Quadro',
    'Quadro',
    'Quadro',
    'Estátua',
    'Taxidermia',
    'Lampião',
    'Relógio de pêndulo',
    'Chapeleira',
    'Mesa decorativa',
    'Vaso decorativo',
    'Vaso decorativo',
    'Vaso decorativo',
    'Mesa com cadeiras',
    'Baú',
    'Távola',
    'Aparador',
    'Criado mudo',
    'Vitral',
    'Cômoda',
    'Mesa redonda',
    'Destroços',
    'Alavanca mecânica',
    'Altar',
    'Fumódromo',
  ],
  'sala_de_energia': [
    'Arquivo de metal',
    'Mesa',
    'Arca',
    'Banqueta',
    'Pia',
    'Balança analítica',
    'Balcão de trabalho',
    'Mesa anti-estática',
    'Gerador a gás',
    'Gerador a óleo',
    'Caixa de Energia',
    'Painel Elétrico',
    'Bomba de água',
    'Forno de descartes',
    'Armário de equipamentos',
    'Gerador a carvão',
    'Nobreak industrial',
    'Exaustor industrial de calor',
    'Armário de sobressalentes',
    'Sistema de combate a incêndio',
    'Hidrante',
    'Latão de lixo',
    'Válvulas de pressão',
    'Monitor computadorizado',
    'Alavanca de pressão',
    'Alavanca mecânica',
    'Alavanca eletrônica',
    'Estação tratamento de água',
    'Tubulação de água',
    'Tubulação de esgoto',
    'Tubulação de gás',
    'Canaleta de cabos',
    'Válvulas de pressão',
    'Válvulas eletrônica',
    'Válvulas mecânica',
    'Monitor computadorizado',
    'Latão de lixo',
    'Armário de ferramentas',
    'Mangueira sobressalente',
    'Destroços',
    'Alavanca de pressão',
    'Alavanca mecânica',
    'Alavanca eletrônica',
    'Caixa de transporte',
    'Caixa metálica',
    'Tijolos',
    'Hastes de metal',
    'Bobina de cabos elétricos',
    'Bobina de cabos lógicos',
    'Mangueira sobressalente',
    'Hastes de ferro',
    'Painel elétrico',
    'Cofre mecânico',
    'Cofre computadorizado',
    'Caixas de metal fechadas',
    'Caixas de plástico fechadas',
    'Caixas de papelão fechadas',
    'Balança industrial',
  ],
  'sala_de_artes': [
    'Carpete',
    'Vaso com plantas',
    'Quadro',
    'Estátua',
    'Taxidermia',
    'Vaso decorativo',
    'Arca',
    'Banqueta',
    'Sofá de um lugar',
    'Tripé com Telescópico',
    'Tripé com Filmadora',
    'Tripé com Câmera',
    'Baú',
    'Távola',
    'Carrinho de chá',
    'Aparador',
    'Lareira',
    'Criado mudo',
    'Vitral',
    'Cômoda',
    'Estante de livros',
    'Guitarra',
    'Violão',
    'Alavanca de pressão',
    'Alavanca mecânica',
    'Alavanca eletrônica',
    'Divã',
    'Altar',
    'Púlpito',
    'Entulhos espalhados',
    'Fonte de água',
    'Piano de cauda',
    'Piano vertical',
  ],
  'lobby': [
    'Carpete',
    'Vaso com plantas',
    'Quadro',
    'Quadro',
    'Quadro',
    'Lampião',
    'Mesa decorativa',
    'Vaso decorativo',
    'Arca',
    'Banqueta',
    'Penteadeira',
    'Banco de madeira de um lugar',
    'Mesa com cadeiras',
    'Baú',
    'Aparador',
    'Criado mudo',
    'Cômoda',
    'Destroços',
    'Divã',
    'Cadeira de balanço',
    'Aparelho de som',
    'Aparelho de CD',
    'Caixa de som',
    'Prateleira de bebidas',
    'Fumódromo',
  ],
  'sala_de_apoio': [
    'Espelho',
    'Carpete',
    'Vaso com plantas',
    'Vaso com plantas',
    'Quadro',
    'Quadro',
    'Quadro',
    'Quadro',
    'Estátua',
    'Relógio eletrônico',
    'Telefone',
    'Câmera de Vigilância',
    'Ventilador',
    'Arca',
    'Banqueta',
    'Pia',
    'Baú',
    'Barril',
    'Carrinho de chá',
    'Estante de talheres',
    'Aparador',
    'Criado mudo',
    'Cômoda',
    'Bancada com pia',
    'Maca',
    'Escrivaninha metálica',
    'Monitor computadorizado',
    'Latão de lixo',
    'Armário de ferramentas',
    'Destroços',
    'Alavanca de pressão',
    'Alavanca mecânica',
    'Alavanca eletrônica',
    'Resma de folhas',
    'Sacos com lençóis',
    'Painel elétrico',
    'Roupas sobressalentes',
    'Pacotes de saco plástico',
    'Cofre mecânico',
    'Cofre computadorizado',
    'Caixas de metal fechadas',
    'Caixas de plástico fechadas',
    'Caixas de papelão fechadas',
    'Estante de talheres',
    'Tanque',
    'Cadeira de madeira',
    'Cadeira de metal',
    'Arara de camisas',
    'Balcão',
  ],
  'enfermaria': [
    'Espelho',
    'Vaso com plantas',
    'Quadro',
    'Quadro',
    'Quadro',
    'Quadro',
    'Computador',
    'Relógio eletrônico',
    'Telefone',
    'Aparelho de Fax',
    'Impressora',
    'Câmera de Vigilância',
    'Cofre manual',
    'Cofre eletrônico',
    'Ventilador',
    'Arquivo de metal',
    'Pia',
    'Espelho de rosto',
    'Banco de madeira de um lugar',
    'Banco de madeira de dois lugares',
    'Banco de madeira de três lugares',
    'Mesa com cadeiras',
    'Baú',
    'Bancada com pia',
    'Maca',
    'Cama de enfermo',
    'Microscópio',
    'Agitador de tubos (vortex)',
    'Berço',
    'Destroços',
    'Alavanca de pressão',
    'Alavanca mecânica',
    'Alavanca eletrônica',
    'Roupas sobressalentes',
    'Pacotes de saco plástico',
    'Cofre mecânico',
    'Cofre computadorizado',
    'Tanque',
    'Alçapão',
    'Entulhos espalhados',
    'Cadeira de madeira',
    'Cadeira de metal',
    'Freezer',
    'Arara de camisas',
  ],
  'crematorio': [
    'Câmara de incineração',
    'Câmara de incineração',
    'Quadro',
    'Quadro',
    'Câmera de Vigilância',
    'Cofre manual',
    'Cofre eletrônico',
    'Baú',
    'Maca',
    'Caixa de Energia',
    'Forno de descartes',
    'Sistema de combate a incêndio',
    'Hidrante',,
    'Latão de lixo',
    'Armário de ferramentas',
    'Destroços',
    'Alavanca de pressão',
    'Alavanca mecânica',
    'Alavanca eletrônica',
    'Caixa de transporte',
    'Caixa metálica',
    'Carrinho de transporte de carga',
    'Carrinho de mão',
    'Hastes de metal',
    'Hastes de ferro',
    'Pacotes de saco plástico',
    'Cofre mecânico',
    'Cofre computadorizado',
    'Caixas de metal fechadas',
    'Caixas de plástico fechadas',
    'Caixas de papelão fechadas',
    'Tanque',
    'Alçapão',
    'Púlpito',
    'Entulhos espalhados',
    'Cadeira de madeira',
    'Cadeira de metal',
  ],
  'sala_secreta': [
    'Quadro',
    'Estátua',
    'Taxidermia',
    'Computador',
    'Notebook',
    'Relógio eletrônico',
    'Câmera de Vigilância',
    'Cofre manual',
    'Cofre eletrônico',
    'Baú',
    'Barril',
    'Computador Científico',
    'Monitor computadorizado',
    'Painel Elétrico',
    'Tubulação de água',
    'Tubulação de esgoto',
    'Tubulação de gás',
    'Destroços',
    'Alavanca de pressão',
    'Alavanca mecânica',
    'Alavanca eletrônica',
    'Painel elétrico',
    'Cofre mecânico',
    'Cofre computadorizado',
    'Molduras sobressalentes',
    'Caixas de metal fechadas',
    'Caixas de plástico fechadas',
    'Caixas de papelão fechadas',
  ],
  'hall': [
    'Espelho',
    'Vaso com plantas',
    'Vaso com plantas',
    'Vaso com plantas',
    'Quadro',
    'Estátua',
    'Taxidermia',
    'Quadro',
    'Estátua',
    'Taxidermia',
    'Quadro',
    'Estátua',
    'Taxidermia',
    'Lampião',
    'Relógio de pêndulo',
    'Chapeleira',
    'Mesa decorativa',
    'Banco de madeira de um lugar',
    'Banco de madeira de dois lugares',
    'Banco de madeira de três lugares',
    'Cristaleira',
    'Baú',
    'Távola',
    'Carrinho de chá',
    'Vitral',
    'Detector de metais',
    'Latão de lixo',
    'Destroços',
    'Alavanca de pressão',
    'Caixa de transporte',
    'Caixa metálica',
    'Estufa de vidro para plantas',
    'Altar',
    'Entulhos espalhados',
    'Fonte de água',
    'Balcão',
    'Fumódromo',
  ],
  'restaurante': [
    'Vaso com plantas',
    'Quadro',
    'Quadro',
    'Quadro',
    'Quadro',
    'Estátua',
    'Taxidermia',
    'Estátua',
    'Taxidermia',
    'Lampião',
    'Relógio de pêndulo',
    'Castiçal de velas',
    'Mesa com cadeiras',
    'Cristaleira',
    'Adega',
    'Carrinho de chá',
    'Estante de talheres',
    'Aparador',
    'Lareira',
    'Vitral',
    'Cômoda',
    'Violão',
    'Destroços',
    'Alavanca de pressão',
    'Alavanca mecânica',
    'Alavanca eletrônica',
    'Altar',
    'Púlpito',
    'Entulhos espalhados',
    'Freezer',
    'Geladeira',
    'Piano de cauda',
    'Piano vertical',
    'Balcão',
    'Prateleira de bebidas',
    'Geladeira de bebidas',
    'Fumódromo',
  ],
  'bar': [
    'Caixa Registradora',
    'Balcão',
    'Vaso com plantas',
    'Quadro',
    'Quadro',
    'Quadro',
    'Estátua',
    'Taxidermia',
    'Estátua',
    'Taxidermia',
    'Lampião',
    'Relógio de pêndulo',
    'Chapeleira',
    'Mesa decorativa',
    'Computador',
    'Relógio eletrônico',
    'Telefone',
    'Câmera de Vigilância',
    'Televisão',
    'Ventilador',
    'Pia',
    'Espelho de rosto',
    'Banco de madeira de um lugar',
    'Banco de madeira de dois lugares',
    'Banco de madeira de três lugares',
    'Tripé com Telescópico',
    'Tripé com Filmadora',
    'Tripé com Câmera',
    'Castiçal de velas',
    'Mesa com cadeiras',
    'Cristaleira',
    'Baú',
    'Barril',
    'Adega',
    'Carrinho de chá',
    'Estante de talheres',
    'Lareira',
    'Criado mudo',
    'Vitral',
    'Guitarra',
    'Violão',
    'Bateria',
    'Escrivaninha metálica',
    'Destroços',
    'Alavanca de pressão',
    'Alavanca mecânica',
    'Alavanca eletrônica',
    'Caixa de transporte',
    'Cofre mecânico',
    'Cofre computadorizado',
    'Caixas de plástico fechadas',
    'Caixas de papelão fechadas',
    'Estante de talheres',
    'Entulhos espalhados',
    'Cadeira de madeira',
    'Cadeira de metal',
    'Freezer',
    'Geladeira',
    'Fogão',
    'Fogão industrial',
    'Forno analógico',
    'Forno de micro-ondas',
    'Aparelho de som',
    'Aparelho de CD',
    'Aparelho de DVD',
    'Caixa de som',
    'Piano de cauda',
    'Piano vertical',
    'Balcão',
    'Prateleira de bebidas',
    'Geladeira de bebidas',
    'Fumódromo',
  ],
  'bercario': [
    'Carpete',
    'Vaso com plantas',
    'Quadro',
    'Quadro',
    'Estátua',
    'Poltrona de um lugar',
    'Poltrona de dois lugares',
    'Telefone',
    'Câmera de Vigilância',
    'Televisão',
    'Ventilador',
    'Vaso decorativo',
    'Arca',
    'Banqueta',
    'Sofá de um lugar',
    'Banco de madeira de um lugar',
    'Banco de madeira de dois lugares',
    'Banco de madeira de três lugares',
    'Tripé com Câmera',
    'Mesa com cadeiras',
    'Baú',
    'Carrinho de chá',
    'Aparador',
    'Criado mudo',
    'Vitral',
    'Cômoda',
    'Estante de livros',
    'Estante de livros',
    'Bancada com pia',
    'Berço',
    'Brinquedos de criança',
    'Brinquedos de criança',
    'Guarda-roupa pequeno',
    'Guarda-roupa médio',
    'Guitarra de enfeite',
    'Violão',
    'Piano',
    'Berço',
    'Balança de bebe',
    'Cama de criança',
    'Fraldário',
    'Fraldário',
    'Armário infantil',
    'Guarda-roupa infantil',
    'Alavanca de pressão',
    'Alavanca mecânica',
    'Roupas sobressalentes',
    'Pacotes de saco plástico',
    'Cofre mecânico',
    'Entulhos espalhados',
    'Cadeira de madeira',
    'Cadeira de balanço',
    'Arara de camisas',
    'Aparelho de som',
    'Aparelho de CD',
    'Caixa de som',
    'Tapete infantil',
    'Tapete infantil',
    'Tapete infantil',
  ],
};

function sortearLugar(tipo,callback) {
  let obrigatorios = [];

  if (tipo == 'bercario') {
    obrigatorios.push('Berço');
    obrigatorios.push('Brinquedos de criança');
  }
  if (tipo == 'bar') {
    obrigatorios.push('Balcão');
    obrigatorios.push('Mesa com cadeiras');
    obrigatorios.push('Mesa com cadeiras');
  }
  if (tipo == 'restaurante') {
    obrigatorios.push('Mesa com cadeiras');
    obrigatorios.push('Mesa com cadeiras');
  }
  if (tipo == 'crematorio') {
    obrigatorios.push('Câmara de incineração');
    obrigatorios.push('Caixão');
  }
  if (tipo == 'enfermaria') {
    obrigatorios.push('Cama de enfermo');
    obrigatorios.push('Estante de medicamentos');
  }
  if (tipo == 'sala_de_artes') {
    obrigatorios.push('Quadro');
    obrigatorios.push('Quadro');
    obrigatorios.push('Quadro');
    obrigatorios.push('Vaso com plantas');

    let tem_estatua = Math.floor(Math.random() * 3) > 1;
    if (tem_estatua) {
      obrigatorios.push('Estátua');
    }

    let tem_taxidermia = Math.floor(Math.random() * 5) > 3;
    if (tem_taxidermia) {
      obrigatorios.push('Taxidermia');
    }
  }
  if (tipo == 'entrada') {
    obrigatorios.push('Detector de metais');
    obrigatorios.push('Quadro');

    let tem_estatua = Math.floor(Math.random() * 3) > 1;
    if (tem_estatua) {
      obrigatorios.push('Estátua');
    }
  }
  if (tipo == 'sala_tecnologica') {
    obrigatorios.push('Computador');
    obrigatorios.push('Escrivaninha');
  }
  if (tipo == 'banheiro') {
    obrigatorios.push('Pia');
    obrigatorios.push('Espelho');
    obrigatorios.push('Vaso sanitário');

    let tem_banheira = Math.floor(Math.random() * 3) > 1;
    if (tem_banheira) {
      obrigatorios.push('Banheira');
    } else {
      obrigatorios.push('Chuveiro');
    }
  }
  if (tipo == 'hall') {
    obrigatorios.push('Estátua');
    obrigatorios.push('Quadro');
    obrigatorios.push('Quadro');
  }
  if (tipo == 'jardim') {
    obrigatorios.push('Estufa de vidro para plantas');
    obrigatorios.push('Vaso com plantas');
    obrigatorios.push('Vaso com plantas');

    let tem_estatua = Math.floor(Math.random() * 3) > 1;
    if (tem_estatua) {
      obrigatorios.push('Estátua');
    }

    let tem_fonte = Math.floor(Math.random() * 3) > 1;
    if (tem_fonte) {
      obrigatorios.push('Fonte de água');
    }
  }
  if (tipo == 'biblioteca') {
    obrigatorios.push('Estante de livros');
    obrigatorios.push('Estante de livros');
    obrigatorios.push('Estante de livros');
  }
  if (tipo == 'sala_de_jantar') {
    obrigatorios.push('Grande mesa com cadeiras');
    obrigatorios.push('Quadro');
  }
  if (tipo == 'cozinha') {
    obrigatorios.push('Fogão');
    obrigatorios.push('Geladeira');
    obrigatorios.push('Pia');
  }
  if (tipo == 'quarto') {
    obrigatorios.push('Guarda-roupa');
    obrigatorios.push('Quadro');

    let cama = Math.floor(Math.random() * 3) > 1;
    if (cama) {
      obrigatorios.push('Cama de solteiro');
    } else {
      obrigatorios.push('Cama de casal');
    }
  }
  if (tipo == 'escritorio') {
    obrigatorios.push('Escrivaninha');
    obrigatorios.push('Computador');

    let tem_mesa = Math.floor(Math.random() * 3) > 1;
    if (tem_mesa) {
      obrigatorios.push('Mesa de trabalho');
    }
  }

  let quantidade = Math.floor(Math.random() * 4) + 3;
  let vetor = [...Array(quantidade).keys()];
  let lista = [];

  vetor.forEach((item, i) => {
    let index = Math.floor(Math.random() * LUGARES[tipo].length);
    lista.push(LUGARES[tipo][index]);

    if (i == (vetor.length - 1)) {
      let final = lista.concat(obrigatorios);

      especializarItens(final,retorno=>{
        formatarItens(retorno,callback);
      });
    }
  });
}

function especializarItem(tipo,callback) {
  if (tipo == 'Taxidermia') {
    rolarTaxidermia(callback);
  } else if (tipo == 'Estátua') {
    rolarEstatua(callback);
  } else if (tipo == 'Quadro') {
    rolarQuadro(callback);
  } else {
    callback(tipo);
  }
}

function especializarItens(lista,callback) {
  let retorno = [];
  lista.forEach((item, i) => {
    especializarItem(item,itemEspecializado=>{
      retorno.push(itemEspecializado);

      if (i == (lista.length - 1)) {
        callback(retorno);
      }
    });
  });
}

function formatarItens(itens,callback) {
  let retorno = '';
  let quebra = '\n\n';

  itens.forEach((item, i) => {
    retorno += `${item}${quebra}`;

    if (i == (itens.length - 1)) {
      callback(retorno);
    }
  });
}
