function rolar(elemento,callback) {
  if (elemento.includes('#')) {
    let tipo = elemento.split('#')[1];
    sortearLugar(tipo,callback);
  } else if (elemento == 'itens') {
    let quantidade = Math.floor(Math.random() * 3) + 1;
    let vetor = [...Array(quantidade).keys()];
    let retorno = '';

    let itens = SCAVENGING.concat(ELEMENTOS[elemento]);

    vetor.forEach((item, i) => {
      let index = Math.floor(Math.random() * itens.length);
      retorno += `${itens[index]}\n`;

      if (i == (vetor.length - 1)) {
        callback(retorno);
      }
    });
  } else if (elemento == 'walkers') {
    let index_walkers_past = Math.floor(Math.random() * WALKERS_PAST.length);
    let index_walkers_wounds = Math.floor(Math.random() * WALKERS_WOUNDS.length);
    callback(`${WALKERS_PAST[index_walkers_past]}\n${WALKERS_WOUNDS[index_walkers_wounds]}`);
  } else if (elemento == 'scavenging') {
    let index = Math.floor(Math.random() * SCAVENGING.length);
    callback(SCAVENGING[index]);
  } else if (elemento == 'npc') {
    rolarNPC(callback);
  } else if (elemento == 'personagens') {
    rolarPersonagem(callback);
  } else if (elemento == 'issues') {
    let issues = NPC_SECRET_ISSUES.concat(NPC_ISSUES);
    let index = Math.floor(Math.random() * issues.length);
    callback(issues[index]);
  } else {
    if (elemento == 'orla') {
      let chance = Math.floor(Math.random() * 10);
      if (chance >= 8) {
          elemento = 'lugares';
      }
    }
    let index = Math.floor(Math.random() * ELEMENTOS[elemento].length);
    callback(ELEMENTOS[elemento][index]);
  }
}

function selecionarSkills(skills,quantidade,callback) {
  if (quantidade == 0) {
    callback(skills,'');
  } else {
    let vetor = [...Array(quantidade).keys()];
    skills = JSON.parse(JSON.stringify(skills));
    let retorno = '';

    vetor.forEach((item, i) => {
      let index = Math.floor(Math.random() * skills.length);
      retorno += (retorno == '') ? skills[index] : `, ${skills[index]}`;
      skills.splice(index, 1);

      if (i == (vetor.length - 1)) {
        callback(skills,retorno);
      }
    });
  }
}

function rolarNPC(callback) {
  let dado = Math.floor(Math.random() * 6) + 1;
  let trained = 0;
  let expert = 0;

  if (dado == 1) {
    // zerado
  } else if (dado == 2) {
    trained = 1;
  } else if (dado == 3) {
    trained = 2;
  } else if (dado == 4) {
    trained = 1;
    expert = 1;
  } else if (dado == 5) {
    trained = 2;
    expert = 1;
  } else {
    trained = 3;
    expert = 2;
  }

  let nome = NOMES[Math.floor(Math.random() * NOMES.length)];
  let idade = Math.floor(Math.random() * 60) + 10;
  let caracteristicas = CARACTERISTICAS[Math.floor(Math.random() * CARACTERISTICAS.length)];
  let npc_issues = NPC_ISSUES[Math.floor(Math.random() * NPC_ISSUES.length)];
  let npc_secret_issues = NPC_SECRET_ISSUES[Math.floor(Math.random() * NPC_SECRET_ISSUES.length)];
  let npc_gear = NPC_GEAR[Math.floor(Math.random() * NPC_GEAR.length)];

  selecionarSkills(SKILLS,trained,(skills,trained_skills)=>{
    selecionarSkills(skills,expert,(skills,expert_skills)=>{
      let npc = `Nome: ${nome}\nIdade: ${idade}\n`;
      npc += `skills (4 dados): ${skills.join(', ')}\nTrained skills (5 dados): ${(trained_skills == '') ? 'Nenhuma' : trained_skills}\nExpert skills (8 dados): ${(expert_skills == '') ? 'Nenhuma' : expert_skills}\n`;
      npc += `Caracteristicas: ${caracteristicas}\n`;
      npc += `Issues: ${npc_issues}\n`;
      npc += `Secret Issues: ${npc_secret_issues}\n`;
      npc += `Gear:\n${npc_gear}\n`;

      rolar('itens',valor=>{
        npc += valor;

        callback(npc);
      });
    });
  });
}

const WALKERS_PAST = [
  'Professor hippie',
  'Criança com brinquedo',
  'Roqueiro punk',
  'Vendedor de carros',
  'Professor de jardim de infância',
  'Paciente de asilo',
  'Nerd da informática',
  'Entusiasta de OVNIs',
  'Avó',
  'Político',
  'Policial',
  'Membro do culto',
  'Caçador',
  'Carpinteiro',
  'Babá',
  'Adolescente gótico',
  'Fanático por esportes',
  'Rico esnobe',
  'Morador de rua',
  'Velho roqueiro',
  'Viciado',
  'Zelador',
  'Garçom',
  'Padre',
  'Entrega de pizza',
  'Coletor de lixo',
  'Celebridade',
  'Carteiro',
  'Jornalista',
  'Soldado',
  'Criança com tiara',
  'Gângster',
  'Adolescente com aparelho',
  'Pregador do Juízo Final',
  'Pessoa excêntrica',
  'Motorista de caminhão',
];

const WALKERS_WOUNDS = [
  'Braço arrancado do corpo',
  'Buraco na barriga, intestinos para fora',
  'Olho comido por pássaros',
  'Um pé pendurado por um fio de músculo',
  'Crânio aberto, com cérebro à mostra',
  'Partes do abdômen comidas',
  'Carne da garganta pendurada',
  'Ferimentos de arma de fogo por toda a parte superior do corpo',
  'Algemas presas a um braço e cortes de faca no rosto',
  'Feridas de lança nas pernas',
  'Ferimento de arma de fogo no peito',
  'Pescoço quebrado',
  'Nariz e lábios arrancados',
  'Podre e quase desmoronando',
  'Corpo seco, esqueleto visível através da pele',
  'Coberto de feridas abertas',
  'Inchado como um balão',
  'Sem braços',
  'Sem maxilar inferior',
  'Quase despedaçado, corpo prestes a desabar',
  'Seta na garganta',
  'Queimado por eletricidade',
  'Muitas feridas de faca',
  'Bandagens podres',
  'Pele comida do rosto',
  'Falta uma mão',
  'Sem cabelo, sem dentes, apenas pele e osso',
  'Pele cozida em água quente',
  'Mofado e cheio de vermes',
  'Meio queimado',
  'Lança quebrada saindo do corpo',
  'Corpo esmagado',
  'Recém-afogado',
  'Carne faltando nas costas e no pescoço (parece bem visto de frente)',
  'Mãos amarradas, tiro no peito',
  'Morreu no leito de doença, com gotejamento de infusão ainda preso',
];

const NPC_GEAR = [
  '',
  'Faca',
  'Lata de alimento',
  'Bastão',
  'Binóculos',
  'Tenda',
  'Canivete',
  'Arco e Flecha',
  'Revólver',
  'Corda',
  'Enlatado',
  'Lança',
  'Cacetete',
  'Carne salgada (2 rações)',
  'Relógio',
  'Capacete',
  'Corrente',
  'Spray de Tinta',
  'Soco inglês',
  'Frutas secas',
  'Garrafa de Água',
];

const CARACTERISTICAS = [
  'Chapéu de caubói',
  'Voz aguda',
  'Rosto marcado',
  'Tatuagem de unicórnio',
  'Risada irritante',
  'Olhar de mil jardas',
  'Parte do corpo amputada',
  'Roupas em cores vivas',
  'Tranças',
  'Piercings por toda parte',
  'Terno e gravata',
  'Barba ou cabelo grande',
  'Extremamente alto',
  'Calções de banho',
  'Rosto bonito e infantil',
  'Olhos intensos',
  'Vestido com trapos',
  'Pele coberta por bolhas',
  'Pés descalços',
  'Vestida com lençóis',
  'Uniforme',
  'Muitos anéis e colares dourados',
  'Oculos de sol',
  'Vestido de spandex',
  'Faltando uma orelha, nariz ou lábios',
  'Cabelo em muitas cores',
  'Marcado por queimadura',
  'Camiseta com carinha sorridente',
  'Jaqueta de couro',
  'Macacão',
  'Smoking canadense',
  'Vestido com peles',
  'Vestido de preto',
  'Capacete, protetores de pulso, cotoveleiras e joelheiras',
  'Código de barras tatuado no pescoço',
  'Colete com asas nas costas',
];

const NPC_ISSUES = [
  'Covarde',
  'Nunca desiste',
  'Busca afirmação',
  'Quer ser o líder',
  'Sempre à procura de problemas',
  'Nunca para de falar',
  'Depressivo',
  'Nervoso',
  'Facilmente insultado',
  'Alcoólico',
  'Sempre faminto',
  'Valentão',
  'Pega o que ele quer',
  'Religioso',
  'Abundante',
  'Coração frio',
  'Obcecado por música',
  'Sacrifica qualquer coisa para sobreviver',
  'Ri do mundo',
  'Esquisito',
  'Apaixona-se facilmente',
  'Não confia em ninguém',
  'Deficientes auditivos',
  'Passado criminoso',
  'Pacifista',
  'Se importa apenas com seu filho/amigo/irmão',
  'Quer construir um novo mundo',
  'Espera o pior de todos',
  'Enlouquece facilmente',
  'Solitário',
  'Quer fazer o que é certo',
  'Gosta de fofocar',
  'Doença terminal',
  'Nunca se lembra do caminho',
  'Não segue regras',
  'Questiona o líder',
];

const NPC_SECRET_ISSUES = [
  'Suicida',
  'Assassino',
  'Viciado em drogas',
  'Mantém seu irmão/irmã/família/amigo trancado em algum lugar',
  'Adora os mortos',
  'Quer matar alguém',
  'Loucamente apaixonado por alguém que não sente o mesmo',
  'Psicopata',
  'Quer ver o mundo queimar',
  'Puni-se',
  'Ouve vozes de comando',
  'Traumatizado',
  'Adora lutar',
  'Traidor',
  'Mentiroso compulsivo',
  'Plano secreto',
  'Quer alguém/algo no grupo',
  'Mentira sobre tudo',
  'Finge ser habilidoso',
  'Mentiras sobre as atrocidades que cometeram',
  'Espalha rumores para ganhar poder',
  'Trabalha secretamente para outra facção',
  'Piromaníaco',
  'Mata seus oponentes',
  'Não se lembra de sua verdadeira identidade',
  'Mentiras sobre o que eles sabem',
  'Mantém um parente morto como animal de estimação',
  'Treinou seus filhos para matar, roubar e mentir',
  'Canibal',
  'Acredita que os mortos são um castigo de Deus',
  'Ladrão',
  'Gosta de atormentar os adversários',
  'Sabe sobre túneis secretos cheios de recursos',
  'Foi mordido',
  'Tem uma doença contagiosa',
  'Droga as pessoas e leva seus equipamentos ou as aprisiona',
  'Deseja matar alguém em particular',
  'Vai roubar os alimentos e fugir sozinho',
  'Vai roubar as armas e fugir sozinho',
  'Vai contar para outra facção como entrar no Refúgio em troca de sua segurança',
  'Matou todos do seu último Refúgio',
  'Não consegue dormir',
  'Tem dupla personalidade, mas não sabe disso',
  'Sonâmbulo',
  'Não tem coragem para atacar ninguém, nem Walkers',
  'Era militar e cumpriu ordens horríveis antes de fugir',
  'Tem ataques de pânico',
  'Fala mal de todos pelas costas',
  'Fala que vai ajudar mas na hora foge',
  'Não confia em ninguém',
  'Não fala a verdade quase nunca',
  'Gasta recursos de forma irresponsável',
  'Não cumpre suas obrigações',
  'Amigo dos Walkers',
  'Cleptomaníaco',
  'Diz ser médico, mas não conhece nada sobre medicina ou primeiros socorros',
  'Bate nos mais fracos',
  'Vai matar alguém dormindo por raiva',
  'Nunca sai do Refúgio, nem para protegê-lo',
];

const ELEMENTOS = {
  lugares: [
    'Hospital',
    'Escola',
    'Faculdade',
    'Academia',
    'Construção destruída',
    'Torre de Água',
    'Praça pública',
    'Parque Aquático',
    'Mercearia',
    'Fábrica',
    'Fábrica',
    'Metalúrgica',
    'Metalúrgica',
    'Metalúrgica',
    'Metalúrgica',
    'Fábrica',
    'Fábrica',
    'Estação de Ônibus',
    'Prédio de Escritório',
    'Prédio de Escritório',
    'Prédio de Escritório',
    'Prédio de Escritório',
    'Casa Suburbana',
    'Casa Suburbana',
    'Casa Suburbana',
    'Casa Suburbana',
    'Casa Suburbana',
    'Casa Suburbana',
    'Casa Suburbana',
    'Casa Suburbana',
    'Casa Suburbana',
    'Casa Suburbana',
    'Casa Suburbana',
    'Casa Suburbana',
    'Casa Suburbana',
    'Casa Suburbana',
    'Casa Suburbana',
    'Hotel',
    'Hotel',
    'Hotel',
    'Hotel',
    'Prisão',
    'Academia de Artes Marciais',
    'Estação de Trem',
    'Estação de Trem',
    'Estúdio de Tatuagem',
    'Estufa',
    'Igreja',
    'Igreja',
    'Igreja',
    'Clube de Hipismo',
    'Jockey Clube',
    'Central Telefônica',
    'Garagem particular',
    'Galpão vazio',
    'Casa em construção',
    'Cinema abandonado',
    'Pizzaria Destruída',
    'Pizzaria',
    'Loja de Instrumentos',
    'Escritório de Contabilidade',
    'Locação de Veículos',
    'Farmácia Queimada',
    'Laboratório de Hemograma',
    'Clínica de Tatuagem',
    'Loja de Ferramentas',
    'Casa de Agrotóxicos',
    'Restaurante Italiano',
    'Restaurante',
    'Fast-food',
    'Restaurante Japonês',
    'Canil',
    'Petshop',
    'Laboratório de Manipulação',
    'Livraria',
    'Lava e Passa',
    'Bar',
    'Pub',
    'Nightclub',
    'Estádio de Baseball',
    'Estádio de Futebol',
    'Estádio de Futebol Americano',
    'Mecânica de carros',
    'Mecânica de motos',
    'Banco',
    'Consulado',
    'Loja de RPG',
    'Loja de Cofres',
    'Loja de Cortinas',
    'Loja de tapetes',
    'Loja de pesca',
    'Shopping (1 andar, 10 lojas)',
    'Shopping (2 andares, 20 lojas)',
    'Shopping (3 andares, 30 lojas)',
    'Loja de CD',
    'Campo de Golf',
    'Prefeitura',
    'Delegacia',
    'Estação de Tratamento de Água',
    'Estação de Energia',
    'Edifício Garagem',
    'Farmácia',
    'Loja de Sapatos',
    'Loja de Roupas',
    'Loja de Roupa Íntima',
    'Parque de Diversão',
    'Jogos Eletrônicos',
    'Relojoaria',
    'Escombros Residenciais',
    'Escombros de Prédio',
    'Escombros de Loja',
    'Posto de gasolina com conveniência',
    'Posto de gasolina sem conveniência',
    'Trailer',
    'Cabanas de acampamento',
    'Alguns trailers',
    'Ônibus adaptado para refúgio',
    'Caminhão adaptado para refúgio',
    'Barco adaptado para refúgio',
    'Motorhome',
    'Helicóptero',
    'Pequeno avião destruído',
    'Torre de vigília particular',
    'Torre de vigília militar',
    'Posto fiscal de trânsito',
    'Heliporto particular',
    'Caminhão de guindaste fixo',
    'Prédio em construção',
    'Casa em construção',
    'Loja em construção',
    'Jardim Infantil',
    'Escola Infantil',
    'Instalação Científica',
    'Abrigo Anti-bombas',
    'Cemitério',
    'Estação de Rádio',
    'Lar dos Idosos',
    'Lar dos Idosos',
    'Teatro',
    'Teatro',
    'Cinema',
    'Padaria',
    'Cinema',
    'Padaria',
    'Farmácia',
    'Armazém',
    'Armazém',
    'Armazém',
    'Estação de Gás',
    'Ponte',
    'Viaduto',
    'Ponte',
    'Viaduto',
    'Museu',
    'Museu',
    'Área residencial',
    'Biblioteca',
    'Faculdade',
    'Parque com playground',
    'Parque ecológico',
    'Zoológico',
  ],
  orla: [
    'Porto de pesca de camarão',
    'Porto de pesca',
    'Doca de reparo',
    'Doca seca de reparo',
    'Porto comercial',
    'Porto de fiscalização',
    'Porto militar',
    'Píer de visitação',
    'Píer de atracamento',
    'Píer militar',
    'Grande guindaste flutuante',
    'Guindaste flutuante',
    'Container',
    'Container adaptado para refugio',
    'Dois containers com cercas',
    'Três containers com cercas',
    'Container destruído',
    'Barco pequeno de pesca',
    'Barco pequeno de transporte',
    'Bote salva-vidas',
    'Bote de madeira',
    'Barco pequeno particular',
    'Barco pequeno policial',
    'Barco pequeno militar',
    'Barco pequeno naufragado',
    'Barco médio de pesca',
    'Barco médio de transporte',
    'Barco médio particular',
    'Barco médio policial',
    'Barco médio militar',
    'Barco médio naufragado',
    'Barco grande de pesca',
    'Barco grande de transporte',
    'Barco grande particular',
    'Barco grande policial',
    'Barco grande militar',
    'Barco grande naufragado',
    'Navio cargueiro',
    'Navio da Marinha',
    'Cruzeiro',
    'Iate particular',
    'Iate militar',
    'Pequena ilha flutuante (boias)',
    'Estação de Trem',
    'Feira municipal',
    'Centro de pesquisa',
    'Ensino fundamental',
    'Oficina de automóveis',
    'Monster Truck encalhado',
    'Carros destruídos',
    'Túnel',
    'Buraco na estrada para um túnel subterrâneo',
    'Delegacia de Polícia',
    'Estádio',
    'Zona industrial',
    'Campo de tiro',
    'Zoológico',
    'Campo de refugiados abandonado',
    'Set de Filmagem',
    'Galpões de Cinema',
    'Tanque de guerra',
    'Túnel',
    'Buraco na estrada para um túnel subterrâneo',
    'Floresta',
    'Floresta',
  ],
  ermos: [
    'Fazenda de plantação',
    'Fazenda de gado',
    'Sítio particular',
    'Sítio arqueológico',
    'Fazenda de plantação com floresta',
    'Fazenda de gado com floresta',
    'Sítio particular com floresta',
    'Sítio arqueológico com floresta',
    'Fazenda de plantação com lago',
    'Fazenda de gado com lago',
    'Sítio particular com lago',
    'Sítio arqueológico com lago',
    'Rancho abandonado',
    'Rancho com charco',
    'Rancho com floresta',
    'Posto de gasolina com conveniência',
    'Posto de gasolina sem conveniência',
    'Floresta',
    'Bar de estrada',
    'Casa de campo pequena',
    'Casa de campo grande',
    'Casa de campo destruída',
    'Posto fiscal',
    'Base militar',
    'Antena de transmissão via satélite',
    'Antena de transmissão de rádio',
    'Ante de transmissão de teve',
    'Aeroporto (1 galpão, 1 base, 1 avião)',
    'Aeroporto (2 galpões, 1 base, 1 avião)',
    'Heliporto (1 galpão, 1 helicóptero)',
    'Construtora de carros',
    'Fábrica',
    'Fábrica',
    'Fábrica',
    'Minas de extração',
    'Aterro sanitário',
    'Depósito de lixo',
    'Galpão quebrado',
    'Galpão',
    'Galpão queimado',
    'Prisão',
    'Igreja',
    'Clube Aquático',
    'Clube de Hipismo',
    'Jockey Clube',
    'Estufa',
    'Estufa',
    'Estação de Trem',
    'Estação de Trem',
    'Instalação Científica',
    'Abrigo Anti-bombas',
    'Cemitério',
    'Ponte',
    'Viaduto',
    'Refúgio abandonado',
    'Estação de esgoto',
    'Escola',
    'Caravana de limusines',
    'Caravana de carros',
    'Caravana de caminhões',
    'Caravana de carroças',
    'Área residencial',
    'Biblioteca',
    'Faculdade',
    'Parque com playground',
    'Parque ecológico',
    'Zoológico',
    'Tanque de guerra',
    'Túnel',
    'Buraco na estrada para um túnel subterrâneo',
    'Estação ferroviária',
    'Centro de pesquisa',
    'Acampamento Militar',
  ],
  itens: [
    'Algema com chaves',
    'Algema sem chaves',
    'Lascas de madeira',
    'Fogão portátil',
    'Fogão portátil queimado',
    'Fogão portátil quebrado',
    'Fogão portátil enferrujado',
    'Pratos',
    'Pratos quebrados',
    'Garfo enferrujado',
    'Garfo quebrado',
    'Garfo',
    'Faca de cozinha',
    'Faca de cozinha enferrujada',
    'Faca de pão',
    'Xícara quebrada',
    'Xícara',
    'Copo grande',
    'Copo de criança',
    'Copo quebrado',
    'Copo',
    'Panela',
    'Frigideira',
    'Panela de Pressão',
    'Panela de ferro',
    'Panela de cerâmica',
    'Panela de inox',
    'Panela de vidro',
    'Panela de alumínio',
    'Pano de prato',
    'Pano de mesa',
    'Escorredor de louça',
    'Tábua',
    'Tábua mofada',
    'Tigela pequena de ferro',
    'Tigela pequena de cerâmica',
    'Tigela pequena de vidro',
    'Tigela pequena de plástico',
    'Tigela grande de ferro',
    'Tigela grande de cerâmica',
    'Tigela grande de vidro',
    'Tigela grande de plástico',
    'Espátula',
    'Pegadores de cozinha',
    'Colher de cozinha',
    'Concha de cozinha',
    'Abridor de lata',
    'Detergente',
    'Esponja',
    'Ralador',
    'Lixeira de cozinha',
    'Lixeira de banheiro',
    'Jarra de Vidro',
    'Jarra de Plástico',
    'Forma de gelo',
    'Rodo de banheiro',
    'Rodo de casa',
    'Espelho pequeno',
    'Espelho de parede médio',
    'Espelho de mão',
    'Prateleira de madeira',
    'Prateleira de ferro',
    'Calendário de papel',
    'Porta escova',
    'Escova de dente',
    'Pasta de dente',
    'Tapete de banheiro',
    'Tapete de porta',
    'Tapete grande',
    'Toalha de mão',
    'Toalha de banho',
    'Roupão de banho',
    'Chinelo',
    'Extensão de tomadas',
    'Adaptador de tomadas',
    'Lâmpada de LED',
    'Lâmpada fluorescente',
    'Lâmpada incandescente',
    'Termômetro',
    'Lençol de solteiro',
    'Lençol de casal',
    'Edredom de solteiro',
    'Edredom de casal',
    'Travesseiro de criança',
    'Travesseiro',
    'Fronha',
    'Frauda de pano',
    'Frauda descartável',
    'Ventilador',
    'Ventilador de teto quebrado',
    'Cabide de plástico',
    'Cabide de ferro',
    'Caixa de joias',
    'Caixa organizadora',
    'Caixa de papéis',
    'Folha de papel',
    'Documentos queimados',
    'Clips de ferro',
    'Clips de plástico',
    'Lata de refrigerante',
    'Lata de molho de tomate',
    'Lata de atum',
    'Lata  tomate',
    'Lata de creme de leite',
    'Lata grão de bico',
    'Lata de milho',
    'Lata de Atum',
    'Lata de sopa',
    'Lata de vegetais',
    'Frutas enlatadas',
    'Lata de Cereais',
    'Saco de Cereais',
    'Macarrão instantâneo',
    'Lata de manteiga de amendoim',
    'Lata de geleia',
    'Saco de balas',
    'Lata de nozes',
    'Caixa de Vitaminas',
    'Vassoura',
    'Vassoura quebrado',
    'Sabão em pó',
    'Sabão de coco',
    'Sabonete',
    'Sabonete de criança',
    'Shampoo',
    'Condicionador',
    'Escovão',
    'Pano de chão',
    'Pá pequena',
    'Pá grande',
    'Pregador de roupa',
    'Varal de fibra',
    'Varal de metal',
    'Balde pequeno de plástico',
    'Balde grande de plástico',
    'Balde pequeno de metal',
    'Balde grande de metal',
    'Esfregão',
    'Esfregão quebrado',
    'Airfryer',
    'Forro de Poltrona',
    'Lascas de madeira',
    'Pregos',
    'Parafusos',
    'Televisão quebrada',
    'Televisão queimada',
    'Pé de Mesa quebrado',
    'Pé de Mesa de plástico',
    'Cacos de vidro',
    'Rolha',
    'Peneira',
    'Garrada de água vazia',
    'Garrada de água',
    'Porta temperos',
    'Isqueiro',
    'Dr Pepper (refrigerante)',
    'Root Beer (não alcoólica)',
    'Cherry Coke',
    'Vinho',
    'Whisky',
    'Vodka',
    'Cerveja',
    'Tequila',
    'Champanhe',
    'Maço de cigarro fechado',
    'Maço de cigarro aberto',
    'Bicicleta quebrada',
    'Bicicleta de criança',
    'Bicicleta',
    'Furadeira quebrada',
    'Furadeira',
    'Parafusadeira quebrada',
    'Parafusadeira',
    'Serra de mão',
    'Serra grande',
    'Lixadeira',
    'Ferro de solda',
    'Chave de fenda',
    'Chave phillips',
    'Martelo',
    'Alicate',
    'Chave allen',
    'Chave biela',
    'Chave de boca',
    'Chave de grifo',
    'Chave inglesa',
    'Espátula',
    'Estilete',
    'Formão',
    'Marreta',
    'Lata de tinta branca',
    'Lata de tinta preta',
    'Lata de tinta vermelha',
    'Lata de tinta vazia',
    'Pé de cabra',
    'Serrote',
    'Bloco de motor de carro',
    'Cilindros (motor de carro)',
    'Pistão (motor de carro)',
    'Anéis de Vedação (motor de carro)',
    'Cabeçote (motor de carro)',
    'Biela (motor de carro)',
    'Virabrequim (motor de carro)',
    'Válvulas (motor de carro)',
    'Vela de ignição (motor de carro)',
    'Correia dentada (motor de carro)',
    'Mangueira de injeção (motor de carro)',
    'Pneu de carro',
    'Pneu de moto',
    'Pneu de bicicleta',
    'Pneu furado de carro',
    'Pneu furado de moto',
    'Pneu furado de bicicleta',
    'Guidão de bicicleta',
    'Aro de bicicleta',
    'Motor de moto',
    'Guidão de moto',
    'Manopla de moto',
    'Freios de moto',
    'Suspensão de moto',
    'Oxímetro',
    'Estetoscópio',
    'Balança de alimentos',
    'Balança de chão',
    'Balança de farmácia',
    'Luvas hospitalares',
    'Máscara hospitalar',
    'Touca hospitalar',
    'Óculos hospitalar',
    'Avental cirúrgico',
    'Desfibriladores',
    'Carrinho de emergência',
    'Maca hospitalar',
    'Termômetro clínico',
    'Tesoura escolar',
    'Tesoura hospitalar',
    'Tesoura de escritório',
    'Papel sulfite',
    'Papel higiênico',
    'Papel de cozinha',
    'Guardanapo',
    'Canetas esferográficas',
    'Lápis',
    'Borracha',
    'Caixa de Grampos',
    'Grampeador',
    'Fita adesiva',
    'Bloco de notas',
    'Agenda',
    'Post-it',
    'Envelope',
    'Dobradiças',
    'Fechadura',
    'Chave',
    'Grampo de cabelo',
    'Gazua',
    'Álcool 70',
    'Algodão',
    'Lixa de unha',
    'Repelente',
    'Medicamento injetável',
    'Antibióticos',
    'Amoxicilina',
    'Antialérgico',
    'Antitérmico',
    'Gaze',
    'Antisséptico',
    'Esparadrapo',
    'Curativos',
    'Analgésicos',
    'Anti-inflamatórios',
    'Medicamento injetável',
    'Antibióticos',
    'Amoxicilina',
    'Antialérgico',
    'Antitérmico',
    'Gaze',
    'Antisséptico',
    'Esparadrapo',
    'Curativos',
    'Analgésicos',
    'Anti-inflamatórios',
    'Antibióticos',
    'Antibióticos',
    'Antibióticos',
    'Antibióticos',
    'Curativos',
    'Curativos',
    'Curativos',
    'Abacaxi',
    'Abacate',
    'Amora',
    'Banana',
    'Caju',
    'Cacau',
    'Damasco',
    'Figo',
    'Alecrim',
    'Tomilho',
    'Sálvia',
    'Orégano',
    'Louro',
    'Salsinha',
    'Cebolinha',
    'Coentro',
    'Livro: Ilíada, de Homero',
    'Livro: Odisseia, de Homero',
    'Livro: Hamlet, de William Shakespeare',
    'Livro: A Divina Comédia, de Dante Alighieri',
    'Livro: Em Busca do Tempo Perdido, de Marcel Proust',
    'Livro: Ulisses, de James Joyce',
    'Livro: Guerra e Paz, de Leon Tosltói',
    'Livro: Crime e Castigo, de Fiódor Dostoiévski',
    'Livro: Os Ensaios, de Michel de Montaigne',
    'Livro: Édipo Rei, de Sófocles',
    'Livro: Otelo, de William Shakespeare',
    'Livro: Madame Bovary, de Gustave Flaubert',
    'Livro: Uma Temporada no Inferno, de Arthur Rimbaud',
    'Livro: Noite de Reis, de William Shakespeare',
    'Livro: Histórias Extraordinárias, de Edgar Allan Poe',
    'Livro: As viagens de Gulliver, de Jonathan Swift',
    'Livro: 1984, de George Orwell',
    'Livro: O Livro das Mil e Uma Noites',
    'Livro: Os Moedeiros Falsos, de André Gide',
    'Livro',
    'Livro',
    'Livro',
    'Livro',
    'Livro',
    'Livro queimado',
    'Livro todo rasgado',
    'Bíblia',
    'Alcorão',
    'Bíblia',
    'Alcorão',
    'Computador',
    'Tela de Computador',
    'Mouse de Computador',
    'Teclado de Computador',
    'Notebook',
    'Cabo de rede de Computador',
    'Telefone de mesa antigo',
    'Telefone de mesa',
    'Celular',
    'Computador',
    'Tela de Computador',
    'Mouse de Computador',
    'Teclado de Computador',
    'Notebook',
    'Cabo de rede de Computador',
    'Telefone de mesa antigo',
    'Telefone de mesa',
    'Celular',
    'Violino',
    'Viola',
    'Violão',
    'Guitarra',
    'Violoncelo',
    'Contrabaixo',
    'Harpa',
    'Teclas de Piano',
    'Violino quebrado',
    'Viola quebrada',
    'Violão quebrado',
    'Guitarra quebrada',
    'Violoncelo quebrado',
    'Contrabaixo quebrado',
    'Harpa quebrada',
    'Teclas de Piano quebradas',
    'Braço decepado',
    'Perna decepada',
    'Cabeça decepada',
    'Dedo decepado',
    'Pé decepado',
    'Orelha decepada',
    'Osso humano da perna',
    'Osso humano do braço',
    'Crânio humano',
    'Cachorro Shih Tzu',
    'Cachorro Yorkshire',
    'Cachorro Poodle',
    'Cachorro Buldogue francês',
    'Cachorro Maltês',
    'Cachorro Golden Retriever',
    'Cachorro Labrador Retriever',
    'Cachorro de rua',
    'Gato de rua',
    'Gato caseiro',
    'Mata mosca',
    'Filé Mignon (carne)',
    'Maminha (carne)',
    'Picanha (carne)',
    'Coxão mole (carne)',
    'Patinho (carne)',
    'Lagarto (carne)',
    'Contrafilé (carne)',
    'Alcatra (carne)',
    'Filé Mignon estragado (carne)',
    'Maminha  estragada (carne)',
    'Picanha  estragada (carne)',
    'Coxão mole  estragado (carne)',
    'Patinho  estragado (carne)',
    'Lagarto  estragado (carne)',
    'Contrafilé  estragado (carne)',
    'Alcatra  estragada (carne)',
    'Tênis',
    'Sapato masculino',
    'Sapato feminino',
    'Meias',
    'Camiseta',
    'Regatas',
    'Calça',
    'Calça jeans',
    'Short',
    'Blazer',
    'Vestido',
    'Casaco',
    'Sobretudo',
    'Jaqueta jeans',
    'Jaqueta couro',
    'Camiseta',
    'Regatas',
    'Calça',
    'Calça jeans',
    'Short',
    'Blazer',
    'Vestido',
    'Casaco',
    'Sobretudo',
    'Jaqueta jeans',
    'Jaqueta couro',
    'Bola de vôlei',
    'Bola de futebol',
    'Bola de futebol Americano',
    'Bola de golfe',
    'Bola de basquete',
    'Bola de sinuca',
    'Fio elétrico pequeno',
    'Fio elétrico grande',
    'Fio elétrico alta tensão',
    'Pistola Beretta',
    'Pistola Glock',
    'Espingarda',
    'Shotgun',
    'Revólver',
    'Rifle',
    'Fuzil',
    'Carabina',
    'Metralhadora',
    'Submetralhadora',
    'Munição de Pistola Beretta',
    'Munição de Pistola Glock',
    'Munição de Espingarda',
    'Munição de Shotgun',
    'Munição de Revólver',
    'Munição de Rifle',
    'Munição de Fuzil',
    'Munição de Carabina',
    'Munição de Metralhadora',
    'Munição de Submetralhadora',
    'Vaso de Filodendro',
    'Vaso de Singônio',
    'Vaso de Cactos',
    'Vaso de Pacová',
    'Vaso de bromélia',
    'Vaso de Lírio',
    'Vaso de Orquídeas',
    'Vaso de Samambaia',
    'Corda de 3 metros',
    'Corda de 10 metros',
    'Corda de 20 metros',
    'Cabo de aço de freio',
    'Cabo de aço de 3 metros',
    'Cabo de aço de 10 metros',
    'Arame farpado',
    'Caixa de fósforos',
    'Vela',
    'Caixa de velas',
    'Sineta',
    'Algibeira',
    'Talha',
    'Tecido Comum',
    'Tecido Fino',
    'Lona',
    'Giz',
    'Ganchos de Ferro',
    'Rede de Pesca',
    'Pederneira',
    'Garrafa de Vidro',
    'Ampulheta',
    'Farolete',
    'Cadeado',
    'Lente de Aumento',
    'Flauta Doce',
    'Tambor',
    'Trombeta',
    'Xilofone',
    'Perfume',
    'Pitons',
    'Aljava com flechas',
    'Arco e flechas',
    'Faca de escoteiro',
    'Faca de açougueiro',
    'Cacete policial',
    'Taco de baseball',
    'Saco Grande',
    'Saco Pequeno',
    'Agulha de Costura',
    'Apito de Advertência',
    'Anel',
    'Pequeno Telescópio',
    'Tenda',
    'Saco de Dormir',
    'Esmeril',
    'Botas de Montaria',
    'Calças',
    'Botas Normais',
    'Vestido Ornamentado',
    'Cinto',
    'Sandálias',
    'Botas de Montaria',
    'Calças',
    'Botas Normais',
    'Vestido Ornamentado',
    'Cinto',
    'Sandálias',
    'Botas de Montaria',
    'Calças',
    'Botas Normais',
    'Vestido Ornamentado',
    'Cinto',
    'Sandálias',
    'Botas de Montaria',
    'Calças',
    'Botas Normais',
    'Vestido Ornamentado',
    'Cinto',
    'Sandálias',
    'Pão',
    'Queijo',
    'Queijo estragado',
    'Queijo mofado',
    'Ovos',
    'Verduras Frescas',
    'Legumes Frescos',
    'Frutas Secas',
    'Frutas Vermelhas',
    'Garrafa de Mel',
    'Coldre de Água',
    'Coldre de Água',
    'Coldre de Água',
    'Coldre de Água',
    'Peixe estragado',
    'Peixe salgado',
    'Peixe fresco',
    'Peixe queimado',
    'Peixe',
    'Peixe',
    'Aquário quebrado',
    'Aquário',
    'Uvas Passas',
    'Saco de Arroz',
    'Saco de Sal',
    'Saco de Arroz',
    'Saco de Sal',
    'Saco de Arroz',
    'Saco de Sal',
    'Pote de Pimenta',
    'Saquinho de Canela',
    'Garrafa de Cidra',
    'Raízes Medicinais',
    'Folhas Medicinais',
    'Frutas Medicinais',
    'Brinco de prata',
    'Colar de prata',
    'Pulseira de prata',
    'Anel de prata',
    'Brinco de ouro',
    'Colar de ouro',
    'Pulseira de ouro',
    'Anel de ouro',
    'Aliança de casamento',
    'Aliança de casamento',
    'Porta retratos',
    'Álbum de retratos queimado',
    'Álbum de retratos',
    'Gaiola',
    'Gaita',
    'Isopor de mantimentos',
    'Macaco de carro',
    'Binóculos',
    'Mapas de Georgia',
    'Câmera fotográfica',
    'Câmera de filmagem',
    'Bússola',
    'Pé de cabra',
    'Pedaços de cavalo morto',
    'Lockpicks (gazua)',
    'Walkie-talkies',
    'Binóculos',
    'Mapas de Georgia',
    'Câmera fotográfica',
    'Câmera de filmagem',
    'Bússola',
    'Pé de cabra',
    'Pedaços de Cavalo morto',
    'Lockpicks (gazua)',
    'Walkie-talkies',
    'Espanador',
    'Coronha do rifle',
    'Faca',
    'Machado pequeno',
    'Pé de cabra',
    'Taco de beisebol',
    'Lança',
    'Espada',
    'Katana',
    'Wakizashi',
    'Tanto (faca japonesa)',
    'Machado grande',
    'Marreta',
    'Coronha do rifle',
    'Faca',
    'Machado pequeno',
    'Pé de cabra',
    'Taco de beisebol',
    'Lança',
    'Espada',
    'Katana',
    'Wakizashi',
    'Tanto (faca japonesa)',
    'Machado grande',
    'Marreta',
    'Faca de arremesso',
    'Arco',
    'Besta',
    'Pistola',
    'Revólver',
    'Espingarda',
    'Rifle',
    'Rifle de precisão',
    'Submetralhadora',
    'Fuzil de assalto',
    'Metralhadora pesada',
    'Coquetel Molotov',
    'Granada de mão',
    'Lançador de foguetes',
    'Faca de arremesso',
    'Arco',
    'Besta',
    'Pistola',
    'Revólver',
    'Espingarda',
    'Rifle',
    'Rifle de precisão',
    'Submetralhadora',
    'Fuzil de assalto',
    'Metralhadora pesada',
    'Coquetel Molotov',
    'Granada de mão',
    'Lançador de foguetes',
    'Relógio de pulso',
    'CD de música',
    'DVD de filme',
    'Cartucho de Vídeo Game',
    'Vídeo Game',
    'Vídeo Game quebrado',
    'Cabo de vídeo',
    'Cabo de áudio',
    'Arame farpado',
    'Ferradura',
    'Pé de mesa',
    'Estaca',
    'Poster de Rock',
    'Bandeira EUA',
    'Bandeira Internacional',
    'Bandeira ONU',
    'Taça de Cristal',
    'Ataduras',
    'Ataduras',
    'Vidros quebrados',
    'Entulhos de obra',
    'Tijolo',
    'Saco de areia',
    'Enxada',
    'Ancinho',
    'Facão',
    'Pássaro morto',
    'Pássaro pequeno',
    'Coruja',
    'Rato morto',
    'Rato',
    'Barata',
    'Inseticida',
    'Escova de dentes',
    'Escova de cabelo',
    'Pasta de dentes',
    'Pasta de dentes',
    'Quadro de parede queimado',
    'Quadro de parede',
    'Pintura de arte',
    'Tinta de pintura',
    'Tinta de criança',
    'Pincel pequeno',
    'Rolo de tinta',
    'Fiação elétrica curta',
    'Fiação elétrica longa',
    'Motor de elevador',
    'Motor a combustão',
    'Motor elétrico',
    'Motor de elevador quebrado',
    'Motor a combustão quebrado',
    'Motor elétrico quebrado',
    'Galão de combustível',
    'Galão de óleo',
    'Lata de óleo de cozinha',
    'Rádio amador',
    'Rádio de caminhão',
    'Rádio de polícia',
    'Farda militar',
    'Farda de policial',
    'Jaleco médico',
    'Sementes de vegetais',
    'Sementes de frutas',
    'Coco de passarinho',
    'Fezes humanas',
    'Fezes de animais',
    'Ladrilho de parede',
    'Livro de RPG',
    'Jogo de cartas',
    'Boneca',
    'Boneco de criança',
    'Carrinho',
    'Massinha de modelar',
    'Jogo de tabuleiro',
    'Bicho de pelúcia',
    'Quebra-cabeça',
    'Manequim',
    'Lanterna pequena',
    'Lanterna grande',
    'Lanterna militar',
    'Mochila de criança',
    'Mochila grande',
    'Mochila militar',
    'Mochila militar rasgada',
    'Bolsa de sangue',
    'Tubo de oxigênio',
    'Tubo de oxigênio',
    'Machado',
    'Lixo orgânico',
    'Lixo hospitalar',
    'Impressora quebrada',
    'Impressora',
    'Alarme de casa',
    'Lata de alumínio',
    'Lata de alumínio',
    'Telha',
    'Telha quebrada',
    'Microfone',
    'Óculos escuros',
    'Óculos de grau',
    'Tesoura de unha',
    'Dentes humanos',
    'Barbante',
    'Vara de pescar',
    'Linha de pescar',
    'Anzol',
    'Escorredor de pratos',
    'Bumerangue',
    'Haste de ferro',
    'Brinquedo de cachorro',
    'Coleira de cachorro',
    'Barbeador',
    'Lâmina de barbear',
    'Cortador de grama',
    'Cortador de grama quebrado',
    'Lascas de vidro',
    'Lascas de ossos',
    'Cifre de animal',
    'Óleo de bronzear',
    'Protetor solar',
    'Revista queimada',
    'Revista rasgada',
    'Revista',
    'Cinto',
    'Soco inglês',
    'Par de Cadarços',
    'Cartão de crédito',
    'Notas de Dólar',
    'Carteira',
    'Armadilha de Urso',
    '3 metros de arame',
    '1 metro de arame',
    'Cacetete',
    'Capacete',
    'Spray de Tinta',
    'Spray de Tinta',
    'Spray de Pimenta',
    'Balde com xixi',
    'Balde com fezes',
    'Um intestino humano enrolado',
    'Um intestino animal',
    'Um dedo cortado',
    'Um pé cortado',
    'Uma orelha cortada',
    'Boné',
    'Chapéu',
  ],
};
